/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderStatusRouteImport } from './routes/order-status'
import { Route as OrderReviewRouteImport } from './routes/order-review'
import { Route as OrderPendingRouteImport } from './routes/order-pending'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as OrderCallbackChoiceRouteImport } from './routes/order-callback-choice'
import { Route as OrderBlockedRouteImport } from './routes/order-blocked'
import { Route as LuxuryRouteImport } from './routes/luxury'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StepIndexRouteImport } from './routes/step.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as StepSlugRouteImport } from './routes/step.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as DevVrSkeletonsRouteImport } from './routes/dev-vr.skeletons'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as ApiPublicWebhooksWooRouteImport } from './routes/api/public/webhooks/woo'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusRoute = OrderStatusRouteImport.update({
  id: '/order-status',
  path: '/order-status',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderReviewRoute = OrderReviewRouteImport.update({
  id: '/order-review',
  path: '/order-review',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderPendingRoute = OrderPendingRouteImport.update({
  id: '/order-pending',
  path: '/order-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCallbackChoiceRoute = OrderCallbackChoiceRouteImport.update({
  id: '/order-callback-choice',
  path: '/order-callback-choice',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderBlockedRoute = OrderBlockedRouteImport.update({
  id: '/order-blocked',
  path: '/order-blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryRoute = LuxuryRouteImport.update({
  id: '/luxury',
  path: '/luxury',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StepIndexRoute = StepIndexRouteImport.update({
  id: '/step/',
  path: '/step/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const StepSlugRoute = StepSlugRouteImport.update({
  id: '/step/$slug',
  path: '/step/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevVrSkeletonsRoute = DevVrSkeletonsRouteImport.update({
  id: '/dev-vr/skeletons',
  path: '/dev-vr/skeletons',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksWooRoute = ApiPublicWebhooksWooRouteImport.update({
  id: '/api/public/webhooks/woo',
  path: '/api/public/webhooks/woo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/luxury': typeof LuxuryRoute
  '/order-blocked': typeof OrderBlockedRoute
  '/order-callback-choice': typeof OrderCallbackChoiceRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/order-pending': typeof OrderPendingRoute
  '/order-review': typeof OrderReviewRoute
  '/order-status': typeof OrderStatusRoute
  '/orders': typeof OrdersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/c/$slug': typeof CSlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/dev-vr/skeletons': typeof DevVrSkeletonsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/step/$slug': typeof StepSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/step/': typeof StepIndexRoute
  '/api/public/webhooks/woo': typeof ApiPublicWebhooksWooRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/luxury': typeof LuxuryRoute
  '/order-blocked': typeof OrderBlockedRoute
  '/order-callback-choice': typeof OrderCallbackChoiceRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/order-pending': typeof OrderPendingRoute
  '/order-review': typeof OrderReviewRoute
  '/order-status': typeof OrderStatusRoute
  '/orders': typeof OrdersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/c/$slug': typeof CSlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/dev-vr/skeletons': typeof DevVrSkeletonsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/step/$slug': typeof StepSlugRoute
  '/products': typeof ProductsIndexRoute
  '/step': typeof StepIndexRoute
  '/api/public/webhooks/woo': typeof ApiPublicWebhooksWooRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/luxury': typeof LuxuryRoute
  '/order-blocked': typeof OrderBlockedRoute
  '/order-callback-choice': typeof OrderCallbackChoiceRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/order-pending': typeof OrderPendingRoute
  '/order-review': typeof OrderReviewRoute
  '/order-status': typeof OrderStatusRoute
  '/orders': typeof OrdersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/c/$slug': typeof CSlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/dev-vr/skeletons': typeof DevVrSkeletonsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/step/$slug': typeof StepSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/step/': typeof StepIndexRoute
  '/api/public/webhooks/woo': typeof ApiPublicWebhooksWooRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/luxury'
    | '/order-blocked'
    | '/order-callback-choice'
    | '/order-confirmed'
    | '/order-pending'
    | '/order-review'
    | '/order-status'
    | '/orders'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/support'
    | '/verify-otp'
    | '/c/$slug'
    | '/collection/$slug'
    | '/dev-vr/skeletons'
    | '/products/$slug'
    | '/step/$slug'
    | '/products/'
    | '/step/'
    | '/api/public/webhooks/woo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/luxury'
    | '/order-blocked'
    | '/order-callback-choice'
    | '/order-confirmed'
    | '/order-pending'
    | '/order-review'
    | '/order-status'
    | '/orders'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/support'
    | '/verify-otp'
    | '/c/$slug'
    | '/collection/$slug'
    | '/dev-vr/skeletons'
    | '/products/$slug'
    | '/step/$slug'
    | '/products'
    | '/step'
    | '/api/public/webhooks/woo'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/luxury'
    | '/order-blocked'
    | '/order-callback-choice'
    | '/order-confirmed'
    | '/order-pending'
    | '/order-review'
    | '/order-status'
    | '/orders'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/support'
    | '/verify-otp'
    | '/c/$slug'
    | '/collection/$slug'
    | '/dev-vr/skeletons'
    | '/products/$slug'
    | '/step/$slug'
    | '/products/'
    | '/step/'
    | '/api/public/webhooks/woo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  LuxuryRoute: typeof LuxuryRoute
  OrderBlockedRoute: typeof OrderBlockedRoute
  OrderCallbackChoiceRoute: typeof OrderCallbackChoiceRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  OrderPendingRoute: typeof OrderPendingRoute
  OrderReviewRoute: typeof OrderReviewRoute
  OrderStatusRoute: typeof OrderStatusRoute
  OrdersRoute: typeof OrdersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  CSlugRoute: typeof CSlugRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  DevVrSkeletonsRoute: typeof DevVrSkeletonsRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  StepSlugRoute: typeof StepSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  StepIndexRoute: typeof StepIndexRoute
  ApiPublicWebhooksWooRoute: typeof ApiPublicWebhooksWooRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-status': {
      id: '/order-status'
      path: '/order-status'
      fullPath: '/order-status'
      preLoaderRoute: typeof OrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-review': {
      id: '/order-review'
      path: '/order-review'
      fullPath: '/order-review'
      preLoaderRoute: typeof OrderReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-pending': {
      id: '/order-pending'
      path: '/order-pending'
      fullPath: '/order-pending'
      preLoaderRoute: typeof OrderPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-callback-choice': {
      id: '/order-callback-choice'
      path: '/order-callback-choice'
      fullPath: '/order-callback-choice'
      preLoaderRoute: typeof OrderCallbackChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-blocked': {
      id: '/order-blocked'
      path: '/order-blocked'
      fullPath: '/order-blocked'
      preLoaderRoute: typeof OrderBlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury': {
      id: '/luxury'
      path: '/luxury'
      fullPath: '/luxury'
      preLoaderRoute: typeof LuxuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step/': {
      id: '/step/'
      path: '/step'
      fullPath: '/step/'
      preLoaderRoute: typeof StepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step/$slug': {
      id: '/step/$slug'
      path: '/step/$slug'
      fullPath: '/step/$slug'
      preLoaderRoute: typeof StepSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-vr/skeletons': {
      id: '/dev-vr/skeletons'
      path: '/dev-vr/skeletons'
      fullPath: '/dev-vr/skeletons'
      preLoaderRoute: typeof DevVrSkeletonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/woo': {
      id: '/api/public/webhooks/woo'
      path: '/api/public/webhooks/woo'
      fullPath: '/api/public/webhooks/woo'
      preLoaderRoute: typeof ApiPublicWebhooksWooRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  LuxuryRoute: LuxuryRoute,
  OrderBlockedRoute: OrderBlockedRoute,
  OrderCallbackChoiceRoute: OrderCallbackChoiceRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  OrderPendingRoute: OrderPendingRoute,
  OrderReviewRoute: OrderReviewRoute,
  OrderStatusRoute: OrderStatusRoute,
  OrdersRoute: OrdersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  CSlugRoute: CSlugRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  DevVrSkeletonsRoute: DevVrSkeletonsRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  StepSlugRoute: StepSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  StepIndexRoute: StepIndexRoute,
  ApiPublicWebhooksWooRoute: ApiPublicWebhooksWooRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
